[package]
name    = "threads-stack"
version = "0.1.0"

[dependencies]
openkal-musl = { path = "../.." }

[targets.threads-stack]
kind = "bin"
main = "src/main.c"

[build]
cxx_runtime = "host-coupled"
